source 'https://rubygems.org'
ruby '2.1.0'
gem 'rails', '4.2.1'
gem 'pg'

gem 'sass-rails', '~> 4.0.3'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'font-awesome-rails'
gem 'jquery-ui-rails', '~> 4.2.1'

gem 'activesupport', '~> 4.2.1'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'js-routes'
gem 'haml'
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
gem 'i18n', :git => 'https://github.com/svenfuchs/i18n.git'
gem 'rails_12factor'
# gem 'd3_rails'
# gem 'net-ldap', '~> 0.3.1'
# gem 'devise', '~> 3.0.0'
# gem 'devise_ldap_authenticatable'

# gem 'figgy'
# gem 'quiet_assets'
# gem 'will_paginate'
# gem 'will_paginate-bootstrap'
# gem 'safe_attributes'
gem 'guard'
gem 'minitest'
# gem 'rb-readline'
gem 'rake', '~> 10.4'
# gem 'whiskey_disk'
# gem 'httparty', '~> 0.11.0'
# gem 'unicorn'
gem 'google-webfonts'
gem 'unirest'
gem 'active_record_query_trace'
gem 'rspec-rails'
gem 'capybara'
gem 'factory_girl_rails'
#   gem 'faker'
  # gem 'cucumber-rails', require: false
# # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
#   gem 'spring'
#   gem 'pry-nav'
#   gem 'launchy'
#
gem 'poltergeist'
gem 'selenium-webdriver'
